name: DVC Pipeline CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-dvc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[s3]"  # include S3 support

      - name: Pull data from DVC remote
        run: dvc pull

      - name: Reproduce DVC Pipeline
        run: dvc repro

      - name: Commit and push metadata
        run: |
          git add .
          git commit -m "Auto-update from CI" || echo "No changes to commit"
          git push origin main

      - name: Push updated data and metrics
        run: dvc push
